apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rsvapp-prod

resources:
  - env.yaml
  - namespace.yaml

bases:
  - ../../app

images:
  - name: mongo
    newTag: "3.3"
    newName: mongo
  - name: rsvp-image
    newTag: latest
    newName: rsvp-image
  